### ISSUE TITLE
Segmentation fault while veriy phase.

### ISSUE THREAD

**Issue by ruimo** [hirakuni45/R8C#23]
Verify中にエラーがあると、Segmentation faultが起きることがある。

**Comment by hirakuni45** [comment]
- 配列を超えてメモリーにアクセスする不具合を認識。
- この修正は行いますが、マスターブランチに対する修正なので、一旦クローズします。
- 修正箇所が少ないので、私の方で、develop ブランチで修正を行い、テスト後に、コミットします。
- その後で master ブランチにマージします。
- ありがとうございました。
